// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type NamedApiResource struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url"`
}
