// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type NamedApiResource struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url"`
}

type NamedApiResourceList struct {
	// Count corresponds to the JSON schema field "count".
	Count int `json:"count"`

	// Next corresponds to the JSON schema field "next".
	Next *string `json:"next"`

	// Previous corresponds to the JSON schema field "previous".
	Previous *string `json:"previous"`

	// Results corresponds to the JSON schema field "results".
	Results []NamedApiResource `json:"results"`
}
