// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type NamedApiResource struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url"`
}

type Nature struct {
	// DecreasedStat corresponds to the JSON schema field "decreased_stat".
	DecreasedStat interface{} `json:"decreased_stat"`

	// HatesFlavor corresponds to the JSON schema field "hates_flavor".
	HatesFlavor interface{} `json:"hates_flavor"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// IncreasedStat corresponds to the JSON schema field "increased_stat".
	IncreasedStat interface{} `json:"increased_stat"`

	// LikesFlavor corresponds to the JSON schema field "likes_flavor".
	LikesFlavor interface{} `json:"likes_flavor"`

	// MoveBattleStylePreferences corresponds to the JSON schema field
	// "move_battle_style_preferences".
	MoveBattleStylePreferences []NatureMoveBattleStylePreferencesElem `json:"move_battle_style_preferences"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Names corresponds to the JSON schema field "names".
	Names []NatureNamesElem `json:"names"`

	// PokeathlonStatChanges corresponds to the JSON schema field
	// "pokeathlon_stat_changes".
	PokeathlonStatChanges []NaturePokeathlonStatChangesElem `json:"pokeathlon_stat_changes"`
}

type NatureMoveBattleStylePreferencesElem struct {
	// HighHpPreference corresponds to the JSON schema field "high_hp_preference".
	HighHpPreference int `json:"high_hp_preference"`

	// LowHpPreference corresponds to the JSON schema field "low_hp_preference".
	LowHpPreference int `json:"low_hp_preference"`

	// MoveBattleStyle corresponds to the JSON schema field "move_battle_style".
	MoveBattleStyle NamedApiResource `json:"move_battle_style"`
}

type NatureNamesElem struct {
	// Language corresponds to the JSON schema field "language".
	Language NamedApiResource `json:"language"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}

type NaturePokeathlonStatChangesElem struct {
	// MaxChange corresponds to the JSON schema field "max_change".
	MaxChange int `json:"max_change"`

	// PokeathlonStat corresponds to the JSON schema field "pokeathlon_stat".
	PokeathlonStat NamedApiResource `json:"pokeathlon_stat"`
}
