// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type NamedApiResource struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url"`
}

type Pokemon struct {
	// Abilities corresponds to the JSON schema field "abilities".
	Abilities []PokemonAbilitiesElem `json:"abilities"`

	// BaseExperience corresponds to the JSON schema field "base_experience".
	BaseExperience *int `json:"base_experience"`

	// Forms corresponds to the JSON schema field "forms".
	Forms []NamedApiResource `json:"forms"`

	// GameIndices corresponds to the JSON schema field "game_indices".
	GameIndices []PokemonGameIndicesElem `json:"game_indices"`

	// Height corresponds to the JSON schema field "height".
	Height int `json:"height"`

	// HeldItems corresponds to the JSON schema field "held_items".
	HeldItems []PokemonHeldItemsElem `json:"held_items"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// IsDefault corresponds to the JSON schema field "is_default".
	IsDefault bool `json:"is_default"`

	// LocationAreaEncounters corresponds to the JSON schema field
	// "location_area_encounters".
	LocationAreaEncounters string `json:"location_area_encounters"`

	// Moves corresponds to the JSON schema field "moves".
	Moves []PokemonMovesElem `json:"moves"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Order corresponds to the JSON schema field "order".
	Order int `json:"order"`

	// PastAbilities corresponds to the JSON schema field "past_abilities".
	PastAbilities []PokemonPastAbilitiesElem `json:"past_abilities"`

	// PastTypes corresponds to the JSON schema field "past_types".
	PastTypes []PokemonPastTypesElem `json:"past_types"`

	// Species corresponds to the JSON schema field "species".
	Species NamedApiResource `json:"species"`

	// Sprites corresponds to the JSON schema field "sprites".
	Sprites PokemonSprites `json:"sprites"`

	// Stats corresponds to the JSON schema field "stats".
	Stats []PokemonStatsElem `json:"stats"`

	// Types corresponds to the JSON schema field "types".
	Types []PokemonTypesElem `json:"types"`

	// Weight corresponds to the JSON schema field "weight".
	Weight int `json:"weight"`
}

type PokemonAbilitiesElem struct {
	// Ability corresponds to the JSON schema field "ability".
	Ability NamedApiResource `json:"ability"`

	// IsHidden corresponds to the JSON schema field "is_hidden".
	IsHidden bool `json:"is_hidden"`

	// Slot corresponds to the JSON schema field "slot".
	Slot int `json:"slot"`
}

type PokemonGameIndicesElem struct {
	// GameIndex corresponds to the JSON schema field "game_index".
	GameIndex int `json:"game_index"`

	// Version corresponds to the JSON schema field "version".
	Version NamedApiResource `json:"version"`
}

type PokemonHeldItemsElem struct {
	// Item corresponds to the JSON schema field "item".
	Item NamedApiResource `json:"item"`

	// VersionDetails corresponds to the JSON schema field "version_details".
	VersionDetails []PokemonHeldItemsElemVersionDetailsElem `json:"version_details"`
}

type PokemonHeldItemsElemVersionDetailsElem struct {
	// Rarity corresponds to the JSON schema field "rarity".
	Rarity int `json:"rarity"`

	// Version corresponds to the JSON schema field "version".
	Version NamedApiResource `json:"version"`
}

type PokemonMovesElem struct {
	// Move corresponds to the JSON schema field "move".
	Move NamedApiResource `json:"move"`

	// VersionGroupDetails corresponds to the JSON schema field
	// "version_group_details".
	VersionGroupDetails []PokemonMovesElemVersionGroupDetailsElem `json:"version_group_details"`
}

type PokemonMovesElemVersionGroupDetailsElem struct {
	// LevelLearnedAt corresponds to the JSON schema field "level_learned_at".
	LevelLearnedAt int `json:"level_learned_at"`

	// MoveLearnMethod corresponds to the JSON schema field "move_learn_method".
	MoveLearnMethod NamedApiResource `json:"move_learn_method"`

	// VersionGroup corresponds to the JSON schema field "version_group".
	VersionGroup NamedApiResource `json:"version_group"`
}

type PokemonPastAbilitiesElem struct {
	// Abilities corresponds to the JSON schema field "abilities".
	Abilities []PokemonPastAbilitiesElemAbilitiesElem `json:"abilities"`

	// Generation corresponds to the JSON schema field "generation".
	Generation NamedApiResource `json:"generation"`
}

type PokemonPastAbilitiesElemAbilitiesElem struct {
	// Ability corresponds to the JSON schema field "ability".
	Ability NamedApiResource `json:"ability"`

	// IsHidden corresponds to the JSON schema field "is_hidden".
	IsHidden bool `json:"is_hidden"`

	// Slot corresponds to the JSON schema field "slot".
	Slot int `json:"slot"`
}

type PokemonPastTypesElem struct {
	// Generation corresponds to the JSON schema field "generation".
	Generation NamedApiResource `json:"generation"`

	// Types corresponds to the JSON schema field "types".
	Types []PokemonPastTypesElemTypesElem `json:"types"`
}

type PokemonPastTypesElemTypesElem struct {
	// Slot corresponds to the JSON schema field "slot".
	Slot int `json:"slot"`

	// Type corresponds to the JSON schema field "type".
	Type NamedApiResource `json:"type"`
}

type PokemonSprites struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackFemale corresponds to the JSON schema field "back_female".
	BackFemale *string `json:"back_female"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyFemale corresponds to the JSON schema field "back_shiny_female".
	BackShinyFemale *string `json:"back_shiny_female"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`

	// Other corresponds to the JSON schema field "other".
	Other PokemonSpritesOther `json:"other"`

	// Versions corresponds to the JSON schema field "versions".
	Versions PokemonSpritesVersions `json:"versions"`
}

type PokemonSpritesOther struct {
	// DreamWorld corresponds to the JSON schema field "dream_world".
	DreamWorld PokemonSpritesOtherDreamWorld `json:"dream_world"`

	// Home corresponds to the JSON schema field "home".
	Home PokemonSpritesOtherHome `json:"home"`

	// OfficialArtwork corresponds to the JSON schema field "official-artwork".
	OfficialArtwork PokemonSpritesOtherOfficialArtwork `json:"official-artwork"`
}

type PokemonSpritesOtherDreamWorld struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`
}

type PokemonSpritesOtherHome struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesOtherOfficialArtwork struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`
}

type PokemonSpritesVersions struct {
	// GenerationI corresponds to the JSON schema field "generation-i".
	GenerationI PokemonSpritesVersionsGenerationI `json:"generation-i"`

	// GenerationIi corresponds to the JSON schema field "generation-ii".
	GenerationIi PokemonSpritesVersionsGenerationIi `json:"generation-ii"`

	// GenerationIii corresponds to the JSON schema field "generation-iii".
	GenerationIii PokemonSpritesVersionsGenerationIii `json:"generation-iii"`

	// GenerationIv corresponds to the JSON schema field "generation-iv".
	GenerationIv PokemonSpritesVersionsGenerationIv `json:"generation-iv"`

	// GenerationV corresponds to the JSON schema field "generation-v".
	GenerationV PokemonSpritesVersionsGenerationV `json:"generation-v"`

	// GenerationVi corresponds to the JSON schema field "generation-vi".
	GenerationVi PokemonSpritesVersionsGenerationVi `json:"generation-vi"`

	// GenerationVii corresponds to the JSON schema field "generation-vii".
	GenerationVii PokemonSpritesVersionsGenerationVii `json:"generation-vii"`

	// GenerationViii corresponds to the JSON schema field "generation-viii".
	GenerationViii PokemonSpritesVersionsGenerationViii `json:"generation-viii"`
}

type PokemonSpritesVersionsGenerationI struct {
	// RedBlue corresponds to the JSON schema field "red-blue".
	RedBlue PokemonSpritesVersionsGenerationIRedBlue `json:"red-blue"`

	// Yellow corresponds to the JSON schema field "yellow".
	Yellow PokemonSpritesVersionsGenerationIYellow `json:"yellow"`
}

type PokemonSpritesVersionsGenerationIRedBlue struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackGray corresponds to the JSON schema field "back_gray".
	BackGray *string `json:"back_gray"`

	// BackTransparent corresponds to the JSON schema field "back_transparent".
	BackTransparent *string `json:"back_transparent"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontGray corresponds to the JSON schema field "front_gray".
	FrontGray *string `json:"front_gray"`

	// FrontTransparent corresponds to the JSON schema field "front_transparent".
	FrontTransparent *string `json:"front_transparent"`
}

type PokemonSpritesVersionsGenerationIYellow struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackGray corresponds to the JSON schema field "back_gray".
	BackGray *string `json:"back_gray"`

	// BackTransparent corresponds to the JSON schema field "back_transparent".
	BackTransparent *string `json:"back_transparent"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontGray corresponds to the JSON schema field "front_gray".
	FrontGray *string `json:"front_gray"`

	// FrontTransparent corresponds to the JSON schema field "front_transparent".
	FrontTransparent *string `json:"front_transparent"`
}

type PokemonSpritesVersionsGenerationIi struct {
	// Crystal corresponds to the JSON schema field "crystal".
	Crystal PokemonSpritesVersionsGenerationIiCrystal `json:"crystal"`

	// Gold corresponds to the JSON schema field "gold".
	Gold PokemonSpritesVersionsGenerationIiGold `json:"gold"`

	// Silver corresponds to the JSON schema field "silver".
	Silver PokemonSpritesVersionsGenerationIiSilver `json:"silver"`
}

type PokemonSpritesVersionsGenerationIiCrystal struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyTransparent corresponds to the JSON schema field
	// "back_shiny_transparent".
	BackShinyTransparent *string `json:"back_shiny_transparent"`

	// BackTransparent corresponds to the JSON schema field "back_transparent".
	BackTransparent *string `json:"back_transparent"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyTransparent corresponds to the JSON schema field
	// "front_shiny_transparent".
	FrontShinyTransparent *string `json:"front_shiny_transparent"`

	// FrontTransparent corresponds to the JSON schema field "front_transparent".
	FrontTransparent *string `json:"front_transparent"`
}

type PokemonSpritesVersionsGenerationIiGold struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontTransparent corresponds to the JSON schema field "front_transparent".
	FrontTransparent *string `json:"front_transparent"`
}

type PokemonSpritesVersionsGenerationIiSilver struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontTransparent corresponds to the JSON schema field "front_transparent".
	FrontTransparent *string `json:"front_transparent"`
}

type PokemonSpritesVersionsGenerationIii struct {
	// Emerald corresponds to the JSON schema field "emerald".
	Emerald PokemonSpritesVersionsGenerationIiiEmerald `json:"emerald"`

	// FireredLeafgreen corresponds to the JSON schema field "firered-leafgreen".
	FireredLeafgreen PokemonSpritesVersionsGenerationIiiFireredLeafgreen `json:"firered-leafgreen"`

	// RubySapphire corresponds to the JSON schema field "ruby-sapphire".
	RubySapphire PokemonSpritesVersionsGenerationIiiRubySapphire `json:"ruby-sapphire"`
}

type PokemonSpritesVersionsGenerationIiiEmerald struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`
}

type PokemonSpritesVersionsGenerationIiiFireredLeafgreen struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`
}

type PokemonSpritesVersionsGenerationIiiRubySapphire struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`
}

type PokemonSpritesVersionsGenerationIv struct {
	// DiamondPearl corresponds to the JSON schema field "diamond-pearl".
	DiamondPearl PokemonSpritesVersionsGenerationIvDiamondPearl `json:"diamond-pearl"`

	// HeartgoldSoulsilver corresponds to the JSON schema field
	// "heartgold-soulsilver".
	HeartgoldSoulsilver PokemonSpritesVersionsGenerationIvHeartgoldSoulsilver `json:"heartgold-soulsilver"`

	// Platinum corresponds to the JSON schema field "platinum".
	Platinum PokemonSpritesVersionsGenerationIvPlatinum `json:"platinum"`
}

type PokemonSpritesVersionsGenerationIvDiamondPearl struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackFemale corresponds to the JSON schema field "back_female".
	BackFemale *string `json:"back_female"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyFemale corresponds to the JSON schema field "back_shiny_female".
	BackShinyFemale *string `json:"back_shiny_female"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationIvHeartgoldSoulsilver struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackFemale corresponds to the JSON schema field "back_female".
	BackFemale *string `json:"back_female"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyFemale corresponds to the JSON schema field "back_shiny_female".
	BackShinyFemale *string `json:"back_shiny_female"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationIvPlatinum struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackFemale corresponds to the JSON schema field "back_female".
	BackFemale *string `json:"back_female"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyFemale corresponds to the JSON schema field "back_shiny_female".
	BackShinyFemale *string `json:"back_shiny_female"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationV struct {
	// BlackWhite corresponds to the JSON schema field "black-white".
	BlackWhite PokemonSpritesVersionsGenerationVBlackWhite `json:"black-white"`
}

type PokemonSpritesVersionsGenerationVBlackWhite struct {
	// Animated corresponds to the JSON schema field "animated".
	Animated PokemonSpritesVersionsGenerationVBlackWhiteAnimated `json:"animated"`

	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackFemale corresponds to the JSON schema field "back_female".
	BackFemale *string `json:"back_female"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyFemale corresponds to the JSON schema field "back_shiny_female".
	BackShinyFemale *string `json:"back_shiny_female"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationVBlackWhiteAnimated struct {
	// BackDefault corresponds to the JSON schema field "back_default".
	BackDefault *string `json:"back_default"`

	// BackFemale corresponds to the JSON schema field "back_female".
	BackFemale *string `json:"back_female"`

	// BackShiny corresponds to the JSON schema field "back_shiny".
	BackShiny *string `json:"back_shiny"`

	// BackShinyFemale corresponds to the JSON schema field "back_shiny_female".
	BackShinyFemale *string `json:"back_shiny_female"`

	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationVi struct {
	// OmegarubyAlphasapphire corresponds to the JSON schema field
	// "omegaruby-alphasapphire".
	OmegarubyAlphasapphire PokemonSpritesVersionsGenerationViOmegarubyAlphasapphire `json:"omegaruby-alphasapphire"`

	// XY corresponds to the JSON schema field "x-y".
	XY PokemonSpritesVersionsGenerationViXY `json:"x-y"`
}

type PokemonSpritesVersionsGenerationViOmegarubyAlphasapphire struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationViXY struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationVii struct {
	// Icons corresponds to the JSON schema field "icons".
	Icons PokemonSpritesVersionsGenerationViiIcons `json:"icons"`

	// UltraSunUltraMoon corresponds to the JSON schema field "ultra-sun-ultra-moon".
	UltraSunUltraMoon PokemonSpritesVersionsGenerationViiUltraSunUltraMoon `json:"ultra-sun-ultra-moon"`
}

type PokemonSpritesVersionsGenerationViiIcons struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`
}

type PokemonSpritesVersionsGenerationViiUltraSunUltraMoon struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`

	// FrontShiny corresponds to the JSON schema field "front_shiny".
	FrontShiny *string `json:"front_shiny"`

	// FrontShinyFemale corresponds to the JSON schema field "front_shiny_female".
	FrontShinyFemale *string `json:"front_shiny_female"`
}

type PokemonSpritesVersionsGenerationViii struct {
	// Icons corresponds to the JSON schema field "icons".
	Icons PokemonSpritesVersionsGenerationViiiIcons `json:"icons"`
}

type PokemonSpritesVersionsGenerationViiiIcons struct {
	// FrontDefault corresponds to the JSON schema field "front_default".
	FrontDefault *string `json:"front_default"`

	// FrontFemale corresponds to the JSON schema field "front_female".
	FrontFemale *string `json:"front_female"`
}

type PokemonStatsElem struct {
	// BaseStat corresponds to the JSON schema field "base_stat".
	BaseStat int `json:"base_stat"`

	// Effort corresponds to the JSON schema field "effort".
	Effort int `json:"effort"`

	// Stat corresponds to the JSON schema field "stat".
	Stat NamedApiResource `json:"stat"`
}

type PokemonTypesElem struct {
	// Slot corresponds to the JSON schema field "slot".
	Slot int `json:"slot"`

	// Type corresponds to the JSON schema field "type".
	Type NamedApiResource `json:"type"`
}
