// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package models

type ApiResource struct {
	// Url corresponds to the JSON schema field "url".
	Url string `json:"url"`
}

type NamedApiResource struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url"`
}

type Stat struct {
	// AffectingMoves corresponds to the JSON schema field "affecting_moves".
	AffectingMoves StatAffectingMoves `json:"affecting_moves"`

	// AffectingNatures corresponds to the JSON schema field "affecting_natures".
	AffectingNatures StatAffectingNatures `json:"affecting_natures"`

	// Characteristics corresponds to the JSON schema field "characteristics".
	Characteristics []ApiResource `json:"characteristics"`

	// GameIndex corresponds to the JSON schema field "game_index".
	GameIndex int `json:"game_index"`

	// ID corresponds to the JSON schema field "id".
	ID int `json:"id"`

	// IsBattleOnly corresponds to the JSON schema field "is_battle_only".
	IsBattleOnly bool `json:"is_battle_only"`

	// MoveDamageClass corresponds to the JSON schema field "move_damage_class".
	MoveDamageClass interface{} `json:"move_damage_class"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`

	// Names corresponds to the JSON schema field "names".
	Names []StatNamesElem `json:"names"`
}

type StatAffectingMoves struct {
	// Decrease corresponds to the JSON schema field "decrease".
	Decrease []StatAffectingMovesDecreaseElem `json:"decrease"`

	// Increase corresponds to the JSON schema field "increase".
	Increase []StatAffectingMovesIncreaseElem `json:"increase"`
}

type StatAffectingMovesDecreaseElem struct {
	// Change corresponds to the JSON schema field "change".
	Change int `json:"change"`

	// Move corresponds to the JSON schema field "move".
	Move NamedApiResource `json:"move"`
}

type StatAffectingMovesIncreaseElem struct {
	// Change corresponds to the JSON schema field "change".
	Change int `json:"change"`

	// Move corresponds to the JSON schema field "move".
	Move NamedApiResource `json:"move"`
}

type StatAffectingNatures struct {
	// Decrease corresponds to the JSON schema field "decrease".
	Decrease []NamedApiResource `json:"decrease"`

	// Increase corresponds to the JSON schema field "increase".
	Increase []NamedApiResource `json:"increase"`
}

type StatNamesElem struct {
	// Language corresponds to the JSON schema field "language".
	Language NamedApiResource `json:"language"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name"`
}
